/**
 * generated by Xtext 2.25.0
 */
package su.nsk.iae.post.poST.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import su.nsk.iae.post.poST.PoSTPackage;
import su.nsk.iae.post.poST.ProgramConfElement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Program Conf Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ProgramConfElementImpl extends MinimalEObjectImpl.Container implements ProgramConfElement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ProgramConfElementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PoSTPackage.Literals.PROGRAM_CONF_ELEMENT;
  }

} //ProgramConfElementImpl
