/**
 * generated by Xtext 2.25.0
 */
package su.nsk.iae.post.poST.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import su.nsk.iae.post.poST.PoSTPackage;
import su.nsk.iae.post.poST.Program;
import su.nsk.iae.post.poST.ProgramConfElements;
import su.nsk.iae.post.poST.ProgramConfiguration;
import su.nsk.iae.post.poST.Task;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Program Configuration</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.post.poST.impl.ProgramConfigurationImpl#getName <em>Name</em>}</li>
 *   <li>{@link su.nsk.iae.post.poST.impl.ProgramConfigurationImpl#getTask <em>Task</em>}</li>
 *   <li>{@link su.nsk.iae.post.poST.impl.ProgramConfigurationImpl#getProgram <em>Program</em>}</li>
 *   <li>{@link su.nsk.iae.post.poST.impl.ProgramConfigurationImpl#getAgrs <em>Agrs</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ProgramConfigurationImpl extends MinimalEObjectImpl.Container implements ProgramConfiguration
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getTask() <em>Task</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTask()
   * @generated
   * @ordered
   */
  protected Task task;

  /**
   * The cached value of the '{@link #getProgram() <em>Program</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProgram()
   * @generated
   * @ordered
   */
  protected Program program;

  /**
   * The cached value of the '{@link #getAgrs() <em>Agrs</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAgrs()
   * @generated
   * @ordered
   */
  protected ProgramConfElements agrs;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ProgramConfigurationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PoSTPackage.Literals.PROGRAM_CONFIGURATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PoSTPackage.PROGRAM_CONFIGURATION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Task getTask()
  {
    if (task != null && task.eIsProxy())
    {
      InternalEObject oldTask = (InternalEObject)task;
      task = (Task)eResolveProxy(oldTask);
      if (task != oldTask)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, PoSTPackage.PROGRAM_CONFIGURATION__TASK, oldTask, task));
      }
    }
    return task;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Task basicGetTask()
  {
    return task;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTask(Task newTask)
  {
    Task oldTask = task;
    task = newTask;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PoSTPackage.PROGRAM_CONFIGURATION__TASK, oldTask, task));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Program getProgram()
  {
    if (program != null && program.eIsProxy())
    {
      InternalEObject oldProgram = (InternalEObject)program;
      program = (Program)eResolveProxy(oldProgram);
      if (program != oldProgram)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, PoSTPackage.PROGRAM_CONFIGURATION__PROGRAM, oldProgram, program));
      }
    }
    return program;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Program basicGetProgram()
  {
    return program;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setProgram(Program newProgram)
  {
    Program oldProgram = program;
    program = newProgram;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PoSTPackage.PROGRAM_CONFIGURATION__PROGRAM, oldProgram, program));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ProgramConfElements getAgrs()
  {
    return agrs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAgrs(ProgramConfElements newAgrs, NotificationChain msgs)
  {
    ProgramConfElements oldAgrs = agrs;
    agrs = newAgrs;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PoSTPackage.PROGRAM_CONFIGURATION__AGRS, oldAgrs, newAgrs);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAgrs(ProgramConfElements newAgrs)
  {
    if (newAgrs != agrs)
    {
      NotificationChain msgs = null;
      if (agrs != null)
        msgs = ((InternalEObject)agrs).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PoSTPackage.PROGRAM_CONFIGURATION__AGRS, null, msgs);
      if (newAgrs != null)
        msgs = ((InternalEObject)newAgrs).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PoSTPackage.PROGRAM_CONFIGURATION__AGRS, null, msgs);
      msgs = basicSetAgrs(newAgrs, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PoSTPackage.PROGRAM_CONFIGURATION__AGRS, newAgrs, newAgrs));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PoSTPackage.PROGRAM_CONFIGURATION__AGRS:
        return basicSetAgrs(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PoSTPackage.PROGRAM_CONFIGURATION__NAME:
        return getName();
      case PoSTPackage.PROGRAM_CONFIGURATION__TASK:
        if (resolve) return getTask();
        return basicGetTask();
      case PoSTPackage.PROGRAM_CONFIGURATION__PROGRAM:
        if (resolve) return getProgram();
        return basicGetProgram();
      case PoSTPackage.PROGRAM_CONFIGURATION__AGRS:
        return getAgrs();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PoSTPackage.PROGRAM_CONFIGURATION__NAME:
        setName((String)newValue);
        return;
      case PoSTPackage.PROGRAM_CONFIGURATION__TASK:
        setTask((Task)newValue);
        return;
      case PoSTPackage.PROGRAM_CONFIGURATION__PROGRAM:
        setProgram((Program)newValue);
        return;
      case PoSTPackage.PROGRAM_CONFIGURATION__AGRS:
        setAgrs((ProgramConfElements)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PoSTPackage.PROGRAM_CONFIGURATION__NAME:
        setName(NAME_EDEFAULT);
        return;
      case PoSTPackage.PROGRAM_CONFIGURATION__TASK:
        setTask((Task)null);
        return;
      case PoSTPackage.PROGRAM_CONFIGURATION__PROGRAM:
        setProgram((Program)null);
        return;
      case PoSTPackage.PROGRAM_CONFIGURATION__AGRS:
        setAgrs((ProgramConfElements)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PoSTPackage.PROGRAM_CONFIGURATION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case PoSTPackage.PROGRAM_CONFIGURATION__TASK:
        return task != null;
      case PoSTPackage.PROGRAM_CONFIGURATION__PROGRAM:
        return program != null;
      case PoSTPackage.PROGRAM_CONFIGURATION__AGRS:
        return agrs != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //ProgramConfigurationImpl
