/**
 * generated by Xtext 2.25.0
 */
package su.nsk.iae.post.poST.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;
import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import su.nsk.iae.post.poST.PoSTPackage;
import su.nsk.iae.post.poST.ProgramConfiguration;
import su.nsk.iae.post.poST.SingleResource;
import su.nsk.iae.post.poST.Task;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Single Resource</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.post.poST.impl.SingleResourceImpl#getTasks <em>Tasks</em>}</li>
 *   <li>{@link su.nsk.iae.post.poST.impl.SingleResourceImpl#getProgramConfs <em>Program Confs</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SingleResourceImpl extends MinimalEObjectImpl.Container implements SingleResource
{
  /**
   * The cached value of the '{@link #getTasks() <em>Tasks</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTasks()
   * @generated
   * @ordered
   */
  protected EList<Task> tasks;

  /**
   * The cached value of the '{@link #getProgramConfs() <em>Program Confs</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProgramConfs()
   * @generated
   * @ordered
   */
  protected EList<ProgramConfiguration> programConfs;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SingleResourceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PoSTPackage.Literals.SINGLE_RESOURCE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Task> getTasks()
  {
    if (tasks == null)
    {
      tasks = new EObjectContainmentEList<Task>(Task.class, this, PoSTPackage.SINGLE_RESOURCE__TASKS);
    }
    return tasks;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ProgramConfiguration> getProgramConfs()
  {
    if (programConfs == null)
    {
      programConfs = new EObjectContainmentEList<ProgramConfiguration>(ProgramConfiguration.class, this, PoSTPackage.SINGLE_RESOURCE__PROGRAM_CONFS);
    }
    return programConfs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PoSTPackage.SINGLE_RESOURCE__TASKS:
        return ((InternalEList<?>)getTasks()).basicRemove(otherEnd, msgs);
      case PoSTPackage.SINGLE_RESOURCE__PROGRAM_CONFS:
        return ((InternalEList<?>)getProgramConfs()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PoSTPackage.SINGLE_RESOURCE__TASKS:
        return getTasks();
      case PoSTPackage.SINGLE_RESOURCE__PROGRAM_CONFS:
        return getProgramConfs();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PoSTPackage.SINGLE_RESOURCE__TASKS:
        getTasks().clear();
        getTasks().addAll((Collection<? extends Task>)newValue);
        return;
      case PoSTPackage.SINGLE_RESOURCE__PROGRAM_CONFS:
        getProgramConfs().clear();
        getProgramConfs().addAll((Collection<? extends ProgramConfiguration>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PoSTPackage.SINGLE_RESOURCE__TASKS:
        getTasks().clear();
        return;
      case PoSTPackage.SINGLE_RESOURCE__PROGRAM_CONFS:
        getProgramConfs().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PoSTPackage.SINGLE_RESOURCE__TASKS:
        return tasks != null && !tasks.isEmpty();
      case PoSTPackage.SINGLE_RESOURCE__PROGRAM_CONFS:
        return programConfs != null && !programConfs.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //SingleResourceImpl
