/*
 * generated by Xtext 2.25.0
 */
package su.nsk.iae.post.ui.wizard;

import org.eclipse.osgi.util.NLS;

public class Messages extends NLS {
	private static final String BUNDLE_NAME = "su.nsk.iae.post.ui.wizard.messages"; //$NON-NLS-1$
	
	public static String HelloWorldFile_Label;
	public static String HelloWorldFile_Description;
	public static String HelloWorldProject_Label;
	public static String HelloWorldProject_Description;
	public static String EmptyFile_Label;
	public static String EmptyFile_Description;
	public static String TemplateFile_Label;
	public static String TemplateFile_Description;
	public static String EmptyTemplateFile_Label;
	public static String EmptyTemplateFile_Description;
	public static String HandDryerFile_Label;
	public static String HandDryerFile_Description;
	public static String EmptyProject_Label;
	public static String EmptyProject_Description;
	public static String EmptyTemplateProject_Label;
	public static String EmptyTemplateProject_Description;
	public static String HandDryerProject_Label;
	public static String HandDryerProject_Description;
	
	static {
	// initialize resource bundle
	NLS.initializeMessages(BUNDLE_NAME, Messages.class);
	}

	private Messages() {
	}
}
