/**
 * generated by Xtext 2.25.0
 */
package su.nsk.iae.post.poST;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Configuration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.post.poST.Configuration#getName <em>Name</em>}</li>
 *   <li>{@link su.nsk.iae.post.poST.Configuration#getConfGlobVars <em>Conf Glob Vars</em>}</li>
 *   <li>{@link su.nsk.iae.post.poST.Configuration#getResources <em>Resources</em>}</li>
 * </ul>
 *
 * @see su.nsk.iae.post.poST.PoSTPackage#getConfiguration()
 * @model
 * @generated
 */
public interface Configuration extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see su.nsk.iae.post.poST.PoSTPackage#getConfiguration_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link su.nsk.iae.post.poST.Configuration#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Conf Glob Vars</b></em>' containment reference list.
   * The list contents are of type {@link su.nsk.iae.post.poST.GlobalVarDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conf Glob Vars</em>' containment reference list.
   * @see su.nsk.iae.post.poST.PoSTPackage#getConfiguration_ConfGlobVars()
   * @model containment="true"
   * @generated
   */
  EList<GlobalVarDeclaration> getConfGlobVars();

  /**
   * Returns the value of the '<em><b>Resources</b></em>' containment reference list.
   * The list contents are of type {@link su.nsk.iae.post.poST.Resource}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Resources</em>' containment reference list.
   * @see su.nsk.iae.post.poST.PoSTPackage#getConfiguration_Resources()
   * @model containment="true"
   * @generated
   */
  EList<Resource> getResources();

} // Configuration
