/**
 * generated by Xtext 2.25.0
 */
package su.nsk.iae.post.poST;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Param Assignment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.post.poST.ParamAssignment#getVariable <em>Variable</em>}</li>
 *   <li>{@link su.nsk.iae.post.poST.ParamAssignment#getAssig <em>Assig</em>}</li>
 *   <li>{@link su.nsk.iae.post.poST.ParamAssignment#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see su.nsk.iae.post.poST.PoSTPackage#getParamAssignment()
 * @model
 * @generated
 */
public interface ParamAssignment extends EObject
{
  /**
   * Returns the value of the '<em><b>Variable</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable</em>' reference.
   * @see #setVariable(SymbolicVariable)
   * @see su.nsk.iae.post.poST.PoSTPackage#getParamAssignment_Variable()
   * @model
   * @generated
   */
  SymbolicVariable getVariable();

  /**
   * Sets the value of the '{@link su.nsk.iae.post.poST.ParamAssignment#getVariable <em>Variable</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable</em>' reference.
   * @see #getVariable()
   * @generated
   */
  void setVariable(SymbolicVariable value);

  /**
   * Returns the value of the '<em><b>Assig</b></em>' attribute.
   * The literals are from the enumeration {@link su.nsk.iae.post.poST.AssignmentType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Assig</em>' attribute.
   * @see su.nsk.iae.post.poST.AssignmentType
   * @see #setAssig(AssignmentType)
   * @see su.nsk.iae.post.poST.PoSTPackage#getParamAssignment_Assig()
   * @model
   * @generated
   */
  AssignmentType getAssig();

  /**
   * Sets the value of the '{@link su.nsk.iae.post.poST.ParamAssignment#getAssig <em>Assig</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Assig</em>' attribute.
   * @see su.nsk.iae.post.poST.AssignmentType
   * @see #getAssig()
   * @generated
   */
  void setAssig(AssignmentType value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(Expression)
   * @see su.nsk.iae.post.poST.PoSTPackage#getParamAssignment_Value()
   * @model containment="true"
   * @generated
   */
  Expression getValue();

  /**
   * Sets the value of the '{@link su.nsk.iae.post.poST.ParamAssignment#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(Expression value);

} // ParamAssignment
