/**
 * generated by Xtext 2.25.0
 */
package su.nsk.iae.post.poST;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Process Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see su.nsk.iae.post.poST.PoSTPackage#getProcessVariable()
 * @model
 * @generated
 */
public interface ProcessVariable extends Variable
{
} // ProcessVariable
