/**
 * generated by Xtext 2.25.0
 */
package su.nsk.iae.post.poST;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Process Template Elements</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.post.poST.ProcessTemplateElements#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see su.nsk.iae.post.poST.PoSTPackage#getProcessTemplateElements()
 * @model
 * @generated
 */
public interface ProcessTemplateElements extends EObject
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link su.nsk.iae.post.poST.AttachVariableConfElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see su.nsk.iae.post.poST.PoSTPackage#getProcessTemplateElements_Elements()
   * @model containment="true"
   * @generated
   */
  EList<AttachVariableConfElement> getElements();

} // ProcessTemplateElements
