/**
 * generated by Xtext 2.25.0
 */
package su.nsk.iae.post.poST;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Program Configuration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.post.poST.ProgramConfiguration#getName <em>Name</em>}</li>
 *   <li>{@link su.nsk.iae.post.poST.ProgramConfiguration#getTask <em>Task</em>}</li>
 *   <li>{@link su.nsk.iae.post.poST.ProgramConfiguration#getProgram <em>Program</em>}</li>
 *   <li>{@link su.nsk.iae.post.poST.ProgramConfiguration#getArgs <em>Args</em>}</li>
 * </ul>
 *
 * @see su.nsk.iae.post.poST.PoSTPackage#getProgramConfiguration()
 * @model
 * @generated
 */
public interface ProgramConfiguration extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see su.nsk.iae.post.poST.PoSTPackage#getProgramConfiguration_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link su.nsk.iae.post.poST.ProgramConfiguration#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Task</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Task</em>' reference.
   * @see #setTask(Task)
   * @see su.nsk.iae.post.poST.PoSTPackage#getProgramConfiguration_Task()
   * @model
   * @generated
   */
  Task getTask();

  /**
   * Sets the value of the '{@link su.nsk.iae.post.poST.ProgramConfiguration#getTask <em>Task</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Task</em>' reference.
   * @see #getTask()
   * @generated
   */
  void setTask(Task value);

  /**
   * Returns the value of the '<em><b>Program</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Program</em>' reference.
   * @see #setProgram(Program)
   * @see su.nsk.iae.post.poST.PoSTPackage#getProgramConfiguration_Program()
   * @model
   * @generated
   */
  Program getProgram();

  /**
   * Sets the value of the '{@link su.nsk.iae.post.poST.ProgramConfiguration#getProgram <em>Program</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Program</em>' reference.
   * @see #getProgram()
   * @generated
   */
  void setProgram(Program value);

  /**
   * Returns the value of the '<em><b>Args</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' containment reference.
   * @see #setArgs(ProgramConfElements)
   * @see su.nsk.iae.post.poST.PoSTPackage#getProgramConfiguration_Args()
   * @model containment="true"
   * @generated
   */
  ProgramConfElements getArgs();

  /**
   * Sets the value of the '{@link su.nsk.iae.post.poST.ProgramConfiguration#getArgs <em>Args</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Args</em>' containment reference.
   * @see #getArgs()
   * @generated
   */
  void setArgs(ProgramConfElements value);

} // ProgramConfiguration
