/**
 * generated by Xtext 2.25.0
 */
package su.nsk.iae.post.poST;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Process Var Init Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.post.poST.ProcessVarInitDeclaration#getVarList <em>Var List</em>}</li>
 *   <li>{@link su.nsk.iae.post.poST.ProcessVarInitDeclaration#getProcess <em>Process</em>}</li>
 * </ul>
 *
 * @see su.nsk.iae.post.poST.PoSTPackage#getProcessVarInitDeclaration()
 * @model
 * @generated
 */
public interface ProcessVarInitDeclaration extends EObject
{
  /**
   * Returns the value of the '<em><b>Var List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var List</em>' containment reference.
   * @see #setVarList(ProcessVarList)
   * @see su.nsk.iae.post.poST.PoSTPackage#getProcessVarInitDeclaration_VarList()
   * @model containment="true"
   * @generated
   */
  ProcessVarList getVarList();

  /**
   * Sets the value of the '{@link su.nsk.iae.post.poST.ProcessVarInitDeclaration#getVarList <em>Var List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var List</em>' containment reference.
   * @see #getVarList()
   * @generated
   */
  void setVarList(ProcessVarList value);

  /**
   * Returns the value of the '<em><b>Process</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Process</em>' reference.
   * @see #setProcess(su.nsk.iae.post.poST.Process)
   * @see su.nsk.iae.post.poST.PoSTPackage#getProcessVarInitDeclaration_Process()
   * @model
   * @generated
   */
  su.nsk.iae.post.poST.Process getProcess();

  /**
   * Sets the value of the '{@link su.nsk.iae.post.poST.ProcessVarInitDeclaration#getProcess <em>Process</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Process</em>' reference.
   * @see #getProcess()
   * @generated
   */
  void setProcess(su.nsk.iae.post.poST.Process value);

} // ProcessVarInitDeclaration
