/**
 * generated by Xtext 2.25.0
 */
package su.nsk.iae.post.poST;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Program Conf Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see su.nsk.iae.post.poST.PoSTPackage#getProgramConfElement()
 * @model
 * @generated
 */
public interface ProgramConfElement extends EObject
{
} // ProgramConfElement
